# Generated by Django 2.1.7 on 2019-02-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenmessage',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
